spring:
  application:
    name: antonyms-query-service
  main:
    web-application-type: none
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
#    instance-id: ${spring.application.name}:${random.value}

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  eager-load:
    enabled: true
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: ["hystrix.stream","info","health"]
      base-path: /actuator
